/*
** A stand-in for SQLite's master internal header, supplying only what
** src/matchertext.c actually uses.
**
** The real sqliteInt.h needs sqlite3.h, parse.h, opcodes.h and keywordhash.h,
** every one of them generated by a full build.  Requiring that build in order
** to exercise a self-contained scanner would defeat the point: this step is
** meant to be isolated, so that a boundary bug is caught here rather than
** surfacing later as a parser failure with a longer explanation.
**
** The test copies this file and matchertext.c into a scratch directory and
** compiles them there.  Nothing is written back into the SQLite tree, and the
** file under test is compiled byte for byte as it is committed.
**
** If matchertext.c ever needs more from sqliteInt.h than the two integer
** widths and assert(), that is a signal worth noticing rather than a line to
** add here: it would mean the scanner has stopped being self-contained.
*/
#ifndef SQLITE_MATCHERTEXT_STUB_H
#define SQLITE_MATCHERTEXT_STUB_H

#include <assert.h>

typedef long long int i64;
typedef unsigned long long int u64;

/* Coverage marker.  Inert here, exactly as in a normal SQLite build. */
#ifndef testcase
# define testcase(X)
#endif

#endif /* SQLITE_MATCHERTEXT_STUB_H */
