"""Stage 5: emit every figure the paper quotes as LaTeX the document can \\input.

The paper must never carry a hand-copied number. This stage writes
doc/generated/, which main.tex pulls in:

  numbers.tex          scalar macros, e.g. \\dataInjectionCVEs
  tbl-mech.tex         containment outcome by syntax (tab:mech)
  tbl-payload-corpus.tex   VERIFY over the fuzzdb/PaTT/SecLists payloads
  tbl-poc-sources.tex  PoC linkage per source
  tbl-anchors.tex      ground-truth CWEs that resolve to an injection label

Macros end in \\xspace so they can be written inline without a trailing {}.
Counts are formatted 13{,}691 and percentages 82\\%, matching the prose style.
"""
import argparse
import csv
import sqlite3
from collections import defaultdict
from pathlib import Path

import export
import matchertext

ROOT = Path(__file__).resolve().parents[1]
DB = ROOT / "data" / "cve.db"
OUT = ROOT / "doc" / "generated"

HEADER = ("%% GENERATED by pipeline/latex.py -- do not edit.\n"
          "%% Regenerate with: python3 pipeline/latex.py\n")

# syntax_type -> the label used in the paper's tables
DISPLAY = {
    "html_dom": "HTML / DOM (XSS)", "sql": "SQL", "ldap": "LDAP", "nosql": "NoSQL",
    "xpath_xquery": "XPath / XQuery", "shell_command": "Shell command",
    "code_eval": "Code / eval", "crlf_header": "CRLF / header",
    "formula_csv": "Formula (CSV)", "template": "Template", "xml": "XML",
    "argument": "Argument", "expression_language": "Expression language",
    "unknown": "Unknown",
}


def num(n):
    return f"{n:,}".replace(",", "{,}")


def pct(x, digits=0):
    return f"{x * 100:.{digits}f}\\%"


def macro(name, value):
    return f"\\newcommand{{\\data{name}}}{{{value}\\xspace}}\n"


def containment(con):
    """Per-syntax inert / rejected / outside over payload-backed CVEs."""
    inert, reject, outside = defaultdict(int), defaultdict(int), defaultdict(int)
    semantic = nonmatcher = 0
    for syn, sk, n in con.execute("""SELECT syntax_type, skeleton, COUNT(*)
                                     FROM syntactic_group GROUP BY group_id"""):
        ok, mech, _ = matchertext.assess(syn, sk)
        if ok:
            (inert if mech == "inert" else reject)[syn] += n
        else:
            outside[syn] += n
            # An outside case fails one of the two threat-model conditions: the
            # sink executes the value, or the context has no matcher delimiters.
            if syn in matchertext.SEMANTIC or syn == "html_dom":
                semantic += n
            else:
                nonmatcher += n
    return inert, reject, outside, semantic, nonmatcher


def tbl_mech(inert, reject, outside):
    hosted = [s for s in DISPLAY if s in matchertext.HOST
              and (inert[s] or reject[s] or outside[s])]
    other = [s for s in DISPLAY if s not in matchertext.HOST and outside[s]]
    lines = ["\\begin{tabular}{lrrr}", "\\toprule",
             "Syntax & Inert embed & Rejected & Outside \\\\", "\\midrule"]
    for s in sorted(hosted, key=lambda s: -(inert[s] + reject[s] + outside[s])):
        lines.append(f"{DISPLAY[s]:<19} & {num(inert[s]):>7} & {num(reject[s]):>3} "
                     f"& {num(outside[s]):>3} \\\\")
    lines.append("\\midrule")
    for s in sorted(other, key=lambda s: -outside[s]):
        lines.append(f"{DISPLAY[s]:<19} & --- & --- & {num(outside[s]):>3} \\\\")
    lines += ["\\midrule",
              f"Total & {num(sum(inert.values()))} & {num(sum(reject.values()))} "
              f"& {num(sum(outside.values()))} \\\\",
              "\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def place(*pairs):
    """Lay out (center_column, text) pairs on one line."""
    line = ""
    for col, text in pairs:
        start = col - len(text) // 2
        line += " " * max(0, start - len(line)) + text
    return line


def fig_tree(grouped, contained, inert, reject, outside, semantic, nonmatcher):
    """The two-decision containment tree.

    Emitted as a complete verbatim block rather than macros, because verbatim
    does not expand them; the paper \\input{}s this file inside its figure.
    """
    p = lambda a, b: f"({round(100 * a / b) if b else 0}%)"
    return "\n".join([
        r"\begin{verbatim}",
        place((35, f"{grouped:,} payload-backed CVEs")),
        "                    ┌──────────"
        "────┴─────────"
        "─────┐",
        "                   yes                            no",
        "       matcher-delimitable context?            OUTSIDE",
        place((20, f"{contained:,} {p(contained, grouped)}"),
              (52, f"{outside:,} {p(outside, grouped)}")),
        "        ┌───────────┴"
        "───────────┐        ┌"
        "──────────┴───"
        "───────┐",
        place((8, "pass"), (32, "fail"), (42, str(semantic)), (64, str(nonmatcher))),
        "    VERIFY(v)               VERIFY(v)  execution sinks       non-matcher delimiters",
        "        ▼                       ▼      templates, eval,      shell ; | &",
        "   INERT EMBED              REJECTED   javascript:           CR/LF, XML <>",
        # (A4) tags the execution-sink branch with the threat-model assumption
        # it violates (threat.tex).
        place((8, f"{inert:,} {p(inert, contained)}"),
              (32, f"{reject:,} {p(reject, contained)}"), (44, "(A4)")),
        r"\end{verbatim}",
    ]) + "\n"


def tbl_payload_corpus(con):
    lines = ["\\begin{tabular}{lrrrr}", "\\toprule",
             "Syntax & Payloads & Inert & Rejected & Outside \\\\", "\\midrule"]
    # mechanism is NULL for non-hostable syntaxes, and SUM over all-NULL
    # comparisons is NULL rather than 0, so count with an explicit CASE.
    for syn, n, i, r, o in con.execute("""
            SELECT syntax_type, COUNT(*),
                   SUM(CASE WHEN mechanism='inert'  THEN 1 ELSE 0 END),
                   SUM(CASE WHEN mechanism='reject' THEN 1 ELSE 0 END),
                   SUM(CASE WHEN preventable=0      THEN 1 ELSE 0 END)
            FROM payload_assessment GROUP BY 1 ORDER BY 2 DESC"""):
        lines.append(f"{DISPLAY.get(syn, syn)} & {num(n)} & {num(i)} & {num(r)} "
                     f"& {num(o)} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def skeleton_count(con, skeleton):
    return con.execute("SELECT COUNT(*) FROM syntactic_group WHERE skeleton=?",
                       (skeleton,)).fetchone()[0]


def tbl_syntax(con, top=6):
    lines = ["\\begin{tabular}{lrr}", "\\toprule",
             "Injection syntax & CVEs & with PoC \\\\", "\\midrule"]
    for syn, n, withpoc in con.execute("""
            SELECT c.syntax_type, COUNT(*),
                   COUNT(DISTINCT CASE WHEN p.cve_id IS NOT NULL THEN c.cve_id END)
            FROM classification c
            LEFT JOIN (SELECT DISTINCT cve_id FROM poc) p USING(cve_id)
            WHERE c.syntax_type <> 'unknown'
            GROUP BY 1 ORDER BY 2 DESC LIMIT ?""", (top,)):
        lines.append(f"{DISPLAY.get(syn, syn):<19} & {num(n):>9} & {num(withpoc):>7} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def tbl_poc_sources(con):
    lines = ["\\begin{tabular}{lrrr}", "\\toprule",
             "Source & PoC rows & CVEs & Injection CVEs \\\\", "\\midrule"]
    for src, rows, cves, inj in con.execute("""
            SELECT p.source, COUNT(*), COUNT(DISTINCT p.cve_id),
                   COUNT(DISTINCT CASE WHEN c.cve_id IS NOT NULL THEN p.cve_id END)
            FROM poc p LEFT JOIN classification c USING(cve_id)
            GROUP BY 1 ORDER BY 2 DESC"""):
        lines.append(f"\\texttt{{{src}}} & {num(rows)} & {num(cves)} & {num(inj)} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def tbl_anchors(rows):
    lines = ["\\begin{tabular}{llrll}", "\\toprule",
             "Suite & CWE & Cases & Family & Syntax \\\\", "\\midrule"]
    for suite, cwe, n, fam, syn in rows:
        lines.append(f"\\texttt{{{suite}}} & {cwe} & {num(n)} & "
                     f"{fam.replace('_', ' ')} & {DISPLAY.get(syn, syn)} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def run(args):
    con = sqlite3.connect(DB)
    q = lambda sql: con.execute(sql).fetchone()[0]
    OUT.mkdir(parents=True, exist_ok=True)

    inert, reject, outside, semantic, nonmatcher = containment(con)
    grouped = sum(inert.values()) + sum(reject.values()) + sum(outside.values())
    contained = sum(inert.values()) + sum(reject.values())

    published = q("SELECT COUNT(*) FROM cve WHERE state='PUBLISHED'")
    injection = q("SELECT COUNT(*) FROM classification")
    with_poc = q("""SELECT COUNT(DISTINCT cve_id) FROM poc
                    WHERE cve_id IN (SELECT cve_id FROM classification)""")

    # Projection: the context condition is readable from the syntax label alone,
    # so it extends to injection CVEs with no payload. The javascript: rate
    # measured on the payload-backed HTML/DOM subset discounts the ceiling.
    hosts = "','".join(sorted(matchertext.HOST))
    hostable = q(f"SELECT COUNT(*) FROM classification WHERE syntax_type IN ('{hosts}')")
    htmldom = q("SELECT COUNT(*) FROM classification WHERE syntax_type='html_dom'")
    hd_backed = inert["html_dom"] + reject["html_dom"] + outside["html_dom"]
    js_rate = outside["html_dom"] / hd_backed if hd_backed else 0
    removed = round(htmldom * js_rate)
    central = hostable - removed

    corpus_n = q("SELECT COUNT(*) FROM payload_assessment")
    corpus_inert = q("SELECT COUNT(*) FROM payload_assessment WHERE mechanism='inert'")
    corpus_reject = q("SELECT COUNT(*) FROM payload_assessment WHERE mechanism='reject'")
    corpus_hostable = corpus_inert + corpus_reject + q(
        f"""SELECT COUNT(*) FROM payload_assessment
            WHERE preventable=0 AND syntax_type IN ('{hosts}')""")

    anchors = [r for r in con.execute("""SELECT suite, cwe_id, COUNT(*) FROM ground_truth
                                         WHERE cwe_id IS NOT NULL GROUP BY 1,2""")]
    from classify import load_hierarchy
    from taxonomy import labels_from_cwes
    parents, _ = load_hierarchy(con)
    resolved = []
    for suite, cwe, n in anchors:
        fam, generic, syn = labels_from_cwes([cwe], parents)
        if fam and not generic:
            resolved.append((suite, cwe, n, fam, syn or ""))
    resolved.sort(key=lambda r: (r[0], -r[2]))

    # Naive-Bayes holdout scores, weighted by class support, from the CSV
    # classify.py writes. Blank precision/recall mean the class never scored.
    nb = list(csv.DictReader(open(ROOT / "data" / "exports" / "nb_holdout.csv")))
    nb_n = sum(int(r["test_n"]) for r in nb) or 1
    wmean = lambda k: sum(float(r[k] or 0) * int(r["test_n"]) for r in nb) / nb_n
    per = {r["class"]: r for r in nb}
    methods = dict(con.execute("SELECT method, COUNT(*) FROM classification GROUP BY 1"))
    n_groups = q("SELECT COUNT(DISTINCT group_id) FROM syntactic_group")
    singletons = q("""SELECT COUNT(*) FROM
        (SELECT group_id FROM syntactic_group GROUP BY 1 HAVING COUNT(*)=1)""")
    # How few containment outcomes the long tail of one-off skeletons reduces to.
    singleton_verdicts = len({
        (s, matchertext.assess(s, sk)[1] or "outside")
        for s, sk in con.execute("""SELECT syntax_type, skeleton FROM syntactic_group
            WHERE group_id IN (SELECT group_id FROM syntactic_group
                               GROUP BY 1 HAVING COUNT(*)=1)""")})

    vals = [
        ("PublishedCVEs", num(published)),
        ("CVERecords", num(q("SELECT COUNT(*) FROM cve"))),
        ("InjectionCVEs", num(injection)),
        ("InjectionShare", pct(injection / published)),
        ("InjectionSharePrecise", pct(injection / published, 1)),
        ("InjectionCWEs", num(q("""SELECT COUNT(DISTINCT cwe_id) FROM cwe_assignment
                                   WHERE cve_id IN (SELECT cve_id FROM classification)"""))),
        ("InjectionKev", num(q("SELECT COUNT(*) FROM classification JOIN kev USING(cve_id)"))),
        # labeling layers
        ("MethodCwe", num(methods.get("cwe", 0))),
        ("MethodCweShare", pct(methods.get("cwe", 0) / injection)),
        ("MethodRule", num(methods.get("rule", 0))),
        ("MethodNb", num(methods.get("nb", 0))),
        ("MethodNbShare", pct(methods.get("nb", 0) / injection, 1)),
        ("MethodUnknown", num(methods.get("unknown", 0))),
        ("NbTestDocs", num(nb_n)),
        ("NbPrecision", f"{wmean('precision'):.3f}"),
        ("NbRecall", f"{wmean('recall'):.3f}"),
        ("NbCoverage", pct(float(nb[0]["coverage"]) if nb else 0)),
        ("NbPrecisionHtmlDom", f"{float(per['html_dom']['precision']):.2f}"),
        ("NbRecallHtmlDom", f"{float(per['html_dom']['recall']):.2f}"),
        ("NbPrecisionSql", f"{float(per['sql']['precision']):.2f}"),
        ("NbRecallSql", f"{float(per['sql']['recall']):.2f}"),
        ("NbPrecisionCodeEval", f"{float(per['code_eval']['precision']):.2f}"),
        ("NbRecallCodeEval", f"{float(per['code_eval']['recall']):.2f}"),
        ("MethodDeterministicShare",
         pct((methods.get("cwe", 0) + methods.get("rule", 0)) / injection, 1)),
        ("AuditPerMethod", num(export.AUDIT_PER_METHOD)),
        ("InjectionWithPoc", num(with_poc)),
        ("InjectionWithPocShare", pct(with_poc / injection)),
        ("PocRows", num(q("SELECT COUNT(*) FROM poc"))),
        # per-source PoC reach over the whole corpus, for \cref{sec:data}
        *[(f"Poc{s.title().replace('-', '')}CVEs", num(n)) for s, n in con.execute(
            "SELECT source, COUNT(DISTINCT cve_id) FROM poc GROUP BY 1 ORDER BY 2 DESC")],
        ("KevRows", num(q("SELECT COUNT(*) FROM kev"))),
        ("VedasScored", num(q("""SELECT COUNT(*) FROM cve v JOIN exploit_score USING(cve_id)
                                 WHERE v.state='PUBLISHED'"""))),
        # payload-backed containment
        ("PayloadBackedCVEs", num(grouped)),
        ("DistinctSkeletons", num(q("SELECT COUNT(DISTINCT group_id) FROM syntactic_group"))),
        ("SingletonGroups", num(singletons)),
        ("SingletonGroupShare", pct(singletons / n_groups)),
        ("SingletonCVEShare", pct(singletons / grouped)),
        ("SingletonVerdicts", num(singleton_verdicts)),
        # The two dominant syntaxes, quoted in results.tex as a share.
        ("TopTwoShare", pct(q("""SELECT COUNT(*) FROM classification
                                 WHERE syntax_type IN ('html_dom','sql')""") / injection)),
        # Counts for the three largest groups the text names, looked up by their
        # exact skeleton so a changed skeleton shows up as 0 rather than silently
        # keeping a stale number.
        *[(f"Group{k}", num(skeleton_count(con, sk))) for k, sk in (
            ("AlertDocId", "< TAG > ALERT ( DOCUMENT . <id> ) </ TAG >"),
            ("AlertCookie", "< TAG > ALERT ( DOCUMENT . COOKIE ) </ TAG >"),
            ("PhpOpen", "< ? <id>"))],
        # orthogonal subclass facets, keyed by (dimension, label)
        *[(f"Sub{d.title().replace('_', '')}{l.title().replace('_', '')}", num(n))
          for d, l, n in con.execute("""SELECT dimension, label, COUNT(*) FROM subclass
                                        WHERE dimension IN ('privilege','technique')
                                        GROUP BY 1,2""")],
        ("Contained", num(contained)),
        ("ContainedShare", pct(contained / grouped)),
        ("InertCVEs", num(sum(inert.values()))),
        ("RejectedCVEs", num(sum(reject.values()))),
        ("OutsideCVEs", num(sum(outside.values()))),
        ("OutsideSemantic", num(semantic)),
        ("OutsideNonmatcher", num(nonmatcher)),
        ("SqlRejected", num(reject["sql"])),
        ("LdapInert", num(inert["ldap"])),
        ("LdapRejected", num(reject["ldap"])),
        # projection onto the full corpus
        ("HostableCVEs", num(hostable)),
        ("HostableShare", pct(hostable / injection)),
        ("HtmlDomCVEs", num(htmldom)),
        ("HtmlDomBacked", num(hd_backed)),
        ("HtmlDomJsSinks", num(outside["html_dom"])),
        ("JsSinkRate", pct(js_rate, 1)),
        ("JsSinkRemoved", num(removed)),
        ("CentralEstimate", num(central)),
        ("CentralShare", pct(central / injection)),
        # payload corpora (fuzzdb / PayloadsAllTheThings / SecLists)
        ("CorpusPayloads", num(corpus_n)),
        ("CorpusHostable", num(corpus_hostable)),
        ("CorpusInert", num(corpus_inert)),
        ("CorpusRejected", num(corpus_reject)),
        ("CorpusInertShare", pct(corpus_inert / (corpus_inert + corpus_reject), 1)),
        ("CorpusRejectedShare", pct(corpus_reject / (corpus_inert + corpus_reject), 1)),
        # labeled ground truth
        ("GroundTruthCases", num(q("SELECT COUNT(*) FROM ground_truth"))),
        ("GroundTruthPairs", num(len(anchors))),
        ("GroundTruthResolved", num(len(resolved))),
    ]
    (OUT / "numbers.tex").write_text(
        HEADER + "".join(macro(k, v) for k, v in vals))
    (OUT / "tbl-mech.tex").write_text(HEADER + tbl_mech(inert, reject, outside))
    (OUT / "fig-tree.tex").write_text(HEADER + fig_tree(
        grouped, contained, sum(inert.values()), sum(reject.values()),
        sum(outside.values()), semantic, nonmatcher))
    (OUT / "tbl-syntax.tex").write_text(HEADER + tbl_syntax(con))
    (OUT / "tbl-payload-corpus.tex").write_text(HEADER + tbl_payload_corpus(con))
    (OUT / "tbl-poc-sources.tex").write_text(HEADER + tbl_poc_sources(con))
    (OUT / "tbl-anchors.tex").write_text(HEADER + tbl_anchors(resolved))
    print(f"wrote {len(vals)} macros and 5 tables to {OUT.relative_to(ROOT)}")
    con.close()


if __name__ == "__main__":
    run(argparse.ArgumentParser(description=__doc__).parse_args())
