"""Stage 5: emit every figure the paper quotes as LaTeX the document can \\input.

The paper must never carry a hand-copied number. This stage writes
doc/generated/, which main.tex pulls in:

  numbers.tex          scalar macros, e.g. \\dataInjectionCVEs
  tbl-mech.tex         containment outcome by syntax (tab:mech)
  tbl-payload-corpus.tex   VERIFY over the fuzzdb/PaTT/SecLists payloads
  tbl-poc-sources.tex  PoC linkage per source
  tbl-anchors.tex      ground-truth CWEs that resolve to an injection label

Macros end in \\xspace so they can be written inline without a trailing {}.
Counts are formatted 13{,}691 and percentages 82\\%, matching the prose style.
"""
import argparse
import csv
import sqlite3
from collections import defaultdict
from pathlib import Path

import export
import matchertext

ROOT = Path(__file__).resolve().parents[1]
DB = ROOT / "data" / "cve.db"
OUT = ROOT / "doc" / "generated"
EXPORTS = ROOT / "data" / "exports"

HEADER = ("%% GENERATED by pipeline/latex.py -- do not edit.\n"
          "%% Regenerate with: python3 pipeline/latex.py\n")

# syntax_type -> the label used in the paper's tables
DISPLAY = {
    "html_dom": "HTML / DOM (XSS)", "sql": "SQL", "ldap": "LDAP", "nosql": "NoSQL",
    "xpath_xquery": "XPath / XQuery", "shell_command": "Shell command",
    "code_eval": "Code / eval", "crlf_header": "CRLF / header",
    "formula_csv": "Formula (CSV)", "template": "Template", "xml": "XML",
    "argument": "Argument", "expression_language": "Expression language",
    "unknown": "Unknown",
}


def num(n):
    return f"{n:,}".replace(",", "{,}")


def pct(x, digits=0):
    return f"{x * 100:.{digits}f}\\%"


def macro(name, value):
    return f"\\newcommand{{\\data{name}}}{{{value}\\xspace}}\n"


def containment(con):
    """Per-syntax inert / rejected / outside over payload-backed CVEs."""
    inert, reject, outside = defaultdict(int), defaultdict(int), defaultdict(int)
    semantic = nonmatcher = 0
    for syn, sk, n in con.execute("""SELECT syntax_type, skeleton, COUNT(*)
                                     FROM syntactic_group GROUP BY group_id"""):
        ok, mech, _ = matchertext.assess(syn, sk)
        if ok:
            (inert if mech == "inert" else reject)[syn] += n
        else:
            outside[syn] += n
            # An outside case fails one of the two threat-model conditions: the
            # sink executes the value, or the context has no matcher delimiters.
            if syn in matchertext.SEMANTIC or syn == "html_dom":
                semantic += n
            else:
                nonmatcher += n
    return inert, reject, outside, semantic, nonmatcher


def post_stratify(con, inert, reject, outside):
    """Reweight the measured containment rate by the corpus syntax mix.

    Payload-backed CVEs are not a random sample of the corpus. SQL is 1.7x
    over-represented, because a SQL injection payload is a literal string a
    write-up can quote, whereas code-eval and argument payloads are usually
    built at run time and never appear verbatim. Payload availability therefore
    correlates with syntax, and specifically with matcher-hostable syntax: 85%
    of the payload-backed subset is hostable against 80% of the corpus.

    Multiplying the pooled containment rate by the corpus inherits that skew and
    overstates the result by roughly five thousand CVEs. Estimating a rate per
    syntax and weighting by the corpus counts removes it, which is the standard
    post-stratification correction.

    A syntax with no payload-backed CVE has no measured rate and falls back to
    the structural rule the model asserts: contained inside HOST, not outside.

    Returns (estimate, [(syntax, corpus_n, backed_n, rate, basis)]).
    """
    corpus = dict(con.execute(
        "SELECT syntax_type, COUNT(*) FROM classification GROUP BY 1"))
    est, rows = 0.0, []
    for syn, n in sorted(corpus.items(), key=lambda kv: -kv[1]):
        backed = inert[syn] + reject[syn] + outside[syn]
        if backed:
            rate, basis = (inert[syn] + reject[syn]) / backed, "measured"
        else:
            rate, basis = (1.0 if syn in matchertext.HOST else 0.0), "structural"
        est += n * rate
        rows.append((syn, n, backed, rate, basis))
    return est, rows


def tbl_strata(rows, top=8):
    lines = ["\\begin{tabular}{lrrr}", "\\toprule",
             "Syntax & CVEs & Payload-backed & Contained \\\\", "\\midrule"]
    for syn, n, backed, rate, basis in rows[:top]:
        mark = "" if basis == "measured" else "$^{\\dagger}$"
        lines.append(f"{DISPLAY.get(syn, syn):<19} & {num(n):>9} & {num(backed):>7}{mark} "
                     f"& {rate * 100:.1f}\\% \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def tbl_mech(inert, reject, outside):
    hosted = [s for s in DISPLAY if s in matchertext.HOST
              and (inert[s] or reject[s] or outside[s])]
    other = [s for s in DISPLAY if s not in matchertext.HOST and outside[s]]
    lines = ["\\begin{tabular}{lrrr}", "\\toprule",
             "Syntax & Inert embed & Rejected & Outside \\\\", "\\midrule"]
    for s in sorted(hosted, key=lambda s: -(inert[s] + reject[s] + outside[s])):
        lines.append(f"{DISPLAY[s]:<19} & {num(inert[s]):>7} & {num(reject[s]):>3} "
                     f"& {num(outside[s]):>3} \\\\")
    lines.append("\\midrule")
    for s in sorted(other, key=lambda s: -outside[s]):
        lines.append(f"{DISPLAY[s]:<19} & --- & --- & {num(outside[s]):>3} \\\\")
    lines += ["\\midrule",
              f"Total & {num(sum(inert.values()))} & {num(sum(reject.values()))} "
              f"& {num(sum(outside.values()))} \\\\",
              "\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def place(*pairs):
    """Lay out (center_column, text) pairs on one line."""
    line = ""
    for col, text in pairs:
        start = col - len(text) // 2
        line += " " * max(0, start - len(line)) + text
    return line


def fig_tree(grouped, contained, inert, reject, outside, semantic, nonmatcher):
    """The two-decision containment tree.

    Emitted as a complete verbatim block rather than macros, because verbatim
    does not expand them; the paper \\input{}s this file inside its figure.
    """
    p = lambda a, b: f"({round(100 * a / b) if b else 0}%)"
    return "\n".join([
        r"\begin{verbatim}",
        place((35, f"{grouped:,} payload-backed CVEs")),
        "                    ┌──────────"
        "────┴─────────"
        "─────┐",
        "                   yes                            no",
        "       matcher-delimitable context?            OUTSIDE",
        place((20, f"{contained:,} {p(contained, grouped)}"),
              (52, f"{outside:,} {p(outside, grouped)}")),
        "        ┌───────────┴"
        "───────────┐        ┌"
        "──────────┴───"
        "───────┐",
        place((8, "pass"), (32, "fail"), (42, str(semantic)), (64, str(nonmatcher))),
        "    VERIFY(v)               VERIFY(v)  execution sinks       non-matcher delimiters",
        "        ▼                       ▼      templates, eval,      shell ; | &",
        "   INERT EMBED              REJECTED   javascript:           CR/LF, XML <>",
        # (A4) tags the execution-sink branch with the threat-model assumption
        # it violates (threat.tex).
        place((8, f"{inert:,} {p(inert, contained)}"),
              (32, f"{reject:,} {p(reject, contained)}"), (44, "(A4)")),
        r"\end{verbatim}",
    ]) + "\n"


def tbl_payload_corpus(con):
    lines = ["\\begin{tabular}{lrrrr}", "\\toprule",
             "Syntax & Payloads & Inert & Rejected & Outside \\\\", "\\midrule"]
    # mechanism is NULL for non-hostable syntaxes, and SUM over all-NULL
    # comparisons is NULL rather than 0, so count with an explicit CASE.
    for syn, n, i, r, o in con.execute("""
            SELECT syntax_type, COUNT(*),
                   SUM(CASE WHEN mechanism='inert'  THEN 1 ELSE 0 END),
                   SUM(CASE WHEN mechanism='reject' THEN 1 ELSE 0 END),
                   SUM(CASE WHEN preventable=0      THEN 1 ELSE 0 END)
            FROM payload_assessment GROUP BY 1 ORDER BY 2 DESC"""):
        lines.append(f"{DISPLAY.get(syn, syn)} & {num(n)} & {num(i)} & {num(r)} "
                     f"& {num(o)} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def skeleton_count(con, skeleton):
    return con.execute("SELECT COUNT(*) FROM syntactic_group WHERE skeleton=?",
                       (skeleton,)).fetchone()[0]


def tbl_syntax(con, top=6):
    """The top syntaxes by count, then an aggregated remainder and a total,
    so the CVEs column sums to \\dataInjectionCVEs and the with-PoC column to
    \\dataInjectionWithPoc rather than leaving the tail unaccounted for."""
    rows = con.execute("""
            SELECT c.syntax_type, COUNT(*) n,
                   COUNT(DISTINCT CASE WHEN p.cve_id IS NOT NULL THEN c.cve_id END) w
            FROM classification c
            LEFT JOIN (SELECT DISTINCT cve_id FROM poc) p USING(cve_id)
            GROUP BY 1 ORDER BY n DESC""").fetchall()
    lines = ["\\begin{tabular}{lrr}", "\\toprule",
             "Injection syntax & CVEs & with PoC \\\\", "\\midrule"]
    for syn, n, w in rows[:top]:
        lines.append(f"{DISPLAY.get(syn, syn):<19} & {num(n):>9} & {num(w):>7} \\\\")
    other = rows[top:]
    lines.append("\\midrule")
    lines.append(f"{('Other (%d types)' % len(other)):<19} "
                 f"& {num(sum(n for _, n, _ in other)):>9} "
                 f"& {num(sum(w for _, _, w in other)):>7} \\\\")
    lines.append("\\midrule")
    lines.append(f"{'Total':<19} & {num(sum(n for _, n, _ in rows)):>9} "
                 f"& {num(sum(w for _, _, w in rows)):>7} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def tbl_poc_sources(con):
    lines = ["\\begin{tabular}{lrrr}", "\\toprule",
             "Source & PoC rows & CVEs & Injection CVEs \\\\", "\\midrule"]
    for src, rows, cves, inj in con.execute("""
            SELECT p.source, COUNT(*), COUNT(DISTINCT p.cve_id),
                   COUNT(DISTINCT CASE WHEN c.cve_id IS NOT NULL THEN p.cve_id END)
            FROM poc p LEFT JOIN classification c USING(cve_id)
            GROUP BY 1 ORDER BY 2 DESC"""):
        lines.append(f"\\texttt{{{src}}} & {num(rows)} & {num(cves)} & {num(inj)} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def tbl_anchors(rows):
    lines = ["\\begin{tabular}{llrll}", "\\toprule",
             "Suite & CWE & Cases & Family & Syntax \\\\", "\\midrule"]
    for suite, cwe, n, fam, syn in rows:
        lines.append(f"\\texttt{{{suite}}} & {cwe} & {num(n)} & "
                     f"{fam.replace('_', ' ')} & {DISPLAY.get(syn, syn)} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


# Arms of the driver experiment, grouped as the table presents them: what a
# caller would write today, what the discipline offers, and what each premise
# costs when it is not met.
SQLI_ARMS = [
    ("concat",       "Concatenated into host SQL", "control"),
    ("ident_concat", "Concatenated as a name",    "control"),
    ("quote",        "\\texttt{\\%Q} escaping",    "legacy"),
    ("escape",       "\\texttt{\\%q} escaping",    "legacy"),
    ("bind",         "Bound parameter",           "legacy"),
    ("mt",           "\\texttt{M'(\\ldots)'} value hole", "mt"),
    ("mt_strict",    "\\textsc{Verify} then \\texttt{M'(\\ldots)'}", "mt"),
    ("ident_mt",     "\\texttt{[\\ldots]} name hole",     "mt"),
]


# The strict build has no in-band holes: the value hole's strict form is the
# typed ?V parameter (mt_v) and the name hole's is ?I (ident_i). Every other
# delivery path splices text through the refused legacy prepare.
STRICT_OF = {"mt": "mt_v", "mt_strict": "mt_v", "ident_mt": "ident_i"}


def tbl_sqli_arms(con):
    """Verdict counts per delivery path, additive build beside strict. In the
    additive default the matcher-delimited holes contain every payload and the
    controls break out. Under strict the legacy prepare is refused, so the typed
    ?V and ?I API is the only path; it contains every payload the same way, and
    every text-splicing path is refused wholesale."""
    add = {a: r for a, *r in con.execute(
        """SELECT arm, SUM(n_inert), SUM(n_breakout), SUM(n_rejected),
                  SUM(n_malformed) FROM mt_sqli_combo GROUP BY arm""")}
    strict = {a: r for a, *r in con.execute(
        """SELECT arm, inert, breakout, rejected, refused, malformed
           FROM mt_sqli_strict""")} \
        if con.execute("""SELECT COUNT(*) FROM sqlite_master
                          WHERE type='table' AND name='mt_sqli_strict'""").fetchone()[0] \
        else {}
    lines = ["\\begin{tabular}{l rrrr rrrr}", "\\toprule",
             "& \\multicolumn{4}{c}{Additive} & \\multicolumn{4}{c}{Strict} \\\\",
             "\\cmidrule(lr){2-5} \\cmidrule(lr){6-9}",
             "Delivery & Inert & Broke out & Refused & Not SQL"
             " & Inert & Broke out & Refused & Not SQL \\\\"]
    last = None
    for arm, label, group in SQLI_ARMS:
        if arm not in add:
            continue
        if group != last:
            lines.append("\\midrule")
            last = group
        src = STRICT_OF.get(arm)
        if src and src in strict:
            si, sb, sr, _, sm = strict[src]      # ?V / ?I: inert, breakout, rejected, malformed
            scells = [si, sb, sr, sm]
        else:                                    # legacy path: refused before the parser
            scells = [0, 0, strict.get(arm, [0, 0, 0, 0, 0])[3], 0]
        cells = list(add[arm]) + scells
        lines.append(f"{label:34} & " + " & ".join(num(v) for v in cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def sqli_macros(con):
    """Scalars the prose quotes. Absent tables mean the stage has not run."""
    if not con.execute("""SELECT COUNT(*) FROM sqlite_master
                          WHERE type='table' AND name='mt_sqli_combo'""").fetchone()[0]:
        return []
    q = lambda sql: con.execute(sql).fetchone()[0]
    def col(c):
        return {a: n for a, n in con.execute(
            f"SELECT arm, SUM({c}) FROM mt_sqli_combo GROUP BY arm")}
    brk, effb = col("n_breakout"), col("n_eff_breakout")
    eff = q("""SELECT COUNT(DISTINCT v.value) FROM mt_sqli_value v
               JOIN mt_sqli_case c USING(value_id) WHERE c.effective=1""")
    vals = [
        ("SqliCases", num(q("SELECT COUNT(*) FROM mt_sqli_case"))),
        ("SqliPayloads", num(q("SELECT COUNT(*) FROM mt_sqli_value"))),
        # The shape of that case count.  Hosts and arms are each typed by hole
        # kind and only compatible pairs run, so the per-payload figure is
        # hosts(value)*arms(value) + hosts(ident)*arms(ident).  Count what
        # appears in mt_sqli_case rather than what mt_sqli_arm declares: the
        # typed ?V and ?I arms are swept separately into mt_sqli_strict.
        ("SqliValueHosts", num(q(
            "SELECT COUNT(DISTINCT host_id) FROM mt_sqli_case "
            "WHERE host_id IN (SELECT host_id FROM mt_sqli_host WHERE hole=1)"))),
        ("SqliIdentHosts", num(q(
            "SELECT COUNT(DISTINCT host_id) FROM mt_sqli_case "
            "WHERE host_id IN (SELECT host_id FROM mt_sqli_host WHERE hole=2)"))),
        ("SqliValueArms", num(q(
            "SELECT COUNT(DISTINCT arm_id) FROM mt_sqli_case "
            "WHERE arm_id IN (SELECT arm_id FROM mt_sqli_arm WHERE hole=1)"))),
        ("SqliIdentArms", num(q(
            "SELECT COUNT(DISTINCT arm_id) FROM mt_sqli_case "
            "WHERE arm_id IN (SELECT arm_id FROM mt_sqli_arm WHERE hole=2)"))),
        ("SqliCasesPerPayload", num(q(
            "SELECT COUNT(*) FROM mt_sqli_case WHERE value_id="
            "(SELECT MIN(value_id) FROM mt_sqli_case)"))),
        ("SqliFamilies", num(q("SELECT COUNT(DISTINCT family) FROM mt_sqli_value"))),
        ("SqliEffective", num(eff)),
        # The shape of the case count: hosts and arms are each typed by hole
        # kind, and only compatible pairs run, so the per-payload figure is
        # hosts(value)*arms(value) + hosts(ident)*arms(ident). Count what
        # appears in mt_sqli_case, not what mt_sqli_arm declares: the typed ?V
        # and ?I strict arms are swept separately into mt_sqli_strict.
        ("SqliValueHosts", num(q(
            "SELECT COUNT(DISTINCT host_id) FROM mt_sqli_case WHERE host_id IN "
            "(SELECT host_id FROM mt_sqli_host WHERE hole=1)"))),
        ("SqliIdentHosts", num(q(
            "SELECT COUNT(DISTINCT host_id) FROM mt_sqli_case WHERE host_id IN "
            "(SELECT host_id FROM mt_sqli_host WHERE hole=2)"))),
        ("SqliValueArms", num(q(
            "SELECT COUNT(DISTINCT arm_id) FROM mt_sqli_case WHERE arm_id IN "
            "(SELECT arm_id FROM mt_sqli_arm WHERE hole=1)"))),
        ("SqliIdentArms", num(q(
            "SELECT COUNT(DISTINCT arm_id) FROM mt_sqli_case WHERE arm_id IN "
            "(SELECT arm_id FROM mt_sqli_arm WHERE hole=2)"))),
        ("SqliCasesPerPayload", num(q(
            "SELECT COUNT(*) FROM mt_sqli_case WHERE value_id="
            "(SELECT MIN(value_id) FROM mt_sqli_case)"))),
        # The only treatment-arm cases that do not compile: payloads carrying a
        # zero byte, which ends a SQLite statement.
        ("SqliIdentMtMalformed", num(q(
            "SELECT COUNT(*) FROM mt_sqli_case c JOIN mt_sqli_arm a USING(arm_id) "
            "WHERE a.name='ident_mt' AND c.verdict='MALFORMED'"))),
        ("SqliNulPayloads", num(q(
            "SELECT COUNT(*) FROM mt_sqli_value WHERE instr(value, char(0))>0"))),
        # the matchertext holes: zero breakouts
        ("SqliMtBreakout", num(brk.get("mt", 0))),
        ("SqliMtStrictBreakout", num(brk.get("mt_strict", 0))),
        ("SqliIdentMtBreakout", num(brk.get("ident_mt", 0))),
        # The only cases in a treatment arm that fail to compile: payloads
        # carrying a zero byte, which ends a SQLite statement.
        ("SqliIdentMtMalformed", num(q(
            """SELECT COUNT(*) FROM mt_sqli_case c JOIN mt_sqli_arm a USING(arm_id)
               WHERE a.name='ident_mt' AND c.verdict='MALFORMED'"""))),
        ("SqliNulPayloads", num(q(
            "SELECT COUNT(*) FROM mt_sqli_value WHERE instr(value, char(0))>0"))),
        # the controls, over the effective set
        ("SqliConcatBreakout", num(effb.get("concat", 0))),
        ("SqliIdentConcatBreakout", num(effb.get("ident_concat", 0))),
        # legacy value defences also hold
        ("SqliQuoteBreakout", num(brk.get("quote", 0))),
        ("SqliBindBreakout", num(brk.get("bind", 0))),
        ("SqliMtStrictRejected", num(q("""SELECT SUM(n_rejected) FROM mt_sqli_combo
                                          WHERE arm='mt_strict'""") or 0)),
    ]
    if con.execute("""SELECT COUNT(*) FROM sqlite_master
                      WHERE type='table' AND name='mt_sqli_strict'""").fetchone()[0]:
        s = {a: r for a, *r in con.execute(
            """SELECT arm, inert, breakout, rejected, refused
               FROM mt_sqli_strict""")}
        v = s.get("mt_v", [0, 0, 0, 0])
        i = s.get("ident_i", [0, 0, 0, 0])
        # the strict typed API: contains every payload, zero breakouts
        vals += [
            ("SqliStrictValueInert", num(v[0])),
            ("SqliStrictValueRejected", num(v[2])),
            ("SqliStrictValueBreakout", num(v[1])),
            ("SqliStrictIdentInert", num(i[0])),
            ("SqliStrictIdentRejected", num(i[2])),
            ("SqliStrictIdentBreakout", num(i[1])),
            # every text-splicing path is refused, the same count per delivery
            ("SqliStrictRefused", num(s.get("concat", [0, 0, 0, 0])[3])),
        ]
    sab = EXPORTS / "sqli_sabotage.csv"
    if sab.exists():
        with open(sab, newline="") as f:
            best = max((float(r["detection_rate"]) for r in csv.DictReader(f)),
                       default=0.0)
        vals.append(("SqliSabotageDetect", pct(best, 1)))
    return vals


def run(args):
    con = sqlite3.connect(DB)
    q = lambda sql: con.execute(sql).fetchone()[0]
    OUT.mkdir(parents=True, exist_ok=True)

    inert, reject, outside, semantic, nonmatcher = containment(con)
    grouped = sum(inert.values()) + sum(reject.values()) + sum(outside.values())
    contained = sum(inert.values()) + sum(reject.values())

    published = q("SELECT COUNT(*) FROM cve WHERE state='PUBLISHED'")
    injection = q("SELECT COUNT(*) FROM classification")
    with_poc = q("""SELECT COUNT(DISTINCT cve_id) FROM poc
                    WHERE cve_id IN (SELECT cve_id FROM classification)""")

    # Projection: the context condition is readable from the syntax label alone,
    # so it extends to injection CVEs with no payload. The javascript: rate
    # measured on the payload-backed HTML/DOM subset discounts the ceiling.
    hosts = "','".join(sorted(matchertext.HOST))
    hostable = q(f"SELECT COUNT(*) FROM classification WHERE syntax_type IN ('{hosts}')")
    htmldom = q("SELECT COUNT(*) FROM classification WHERE syntax_type='html_dom'")
    hd_backed = inert["html_dom"] + reject["html_dom"] + outside["html_dom"]
    js_rate = outside["html_dom"] / hd_backed if hd_backed else 0
    removed = round(htmldom * js_rate)
    # Post-stratified rather than the pooled rate applied to the whole corpus.
    # The naive form is kept only so the paper can show what the skew costs.
    strat, strata = post_stratify(con, inert, reject, outside)
    central = round(strat)
    naive = contained / grouped * injection

    corpus_n = q("SELECT COUNT(*) FROM payload_assessment")
    corpus_inert = q("SELECT COUNT(*) FROM payload_assessment WHERE mechanism='inert'")
    corpus_reject = q("SELECT COUNT(*) FROM payload_assessment WHERE mechanism='reject'")
    corpus_hostable = corpus_inert + corpus_reject + q(
        f"""SELECT COUNT(*) FROM payload_assessment
            WHERE preventable=0 AND syntax_type IN ('{hosts}')""")

    anchors = [r for r in con.execute("""SELECT suite, cwe_id, COUNT(*) FROM ground_truth
                                         WHERE cwe_id IS NOT NULL GROUP BY 1,2""")]
    from classify import load_hierarchy
    from taxonomy import labels_from_cwes
    parents, _ = load_hierarchy(con)
    resolved = []
    for suite, cwe, n in anchors:
        fam, generic, syn = labels_from_cwes([cwe], parents)
        if fam and not generic:
            resolved.append((suite, cwe, n, fam, syn or ""))
    resolved.sort(key=lambda r: (r[0], -r[2]))

    # Naive-Bayes holdout scores, weighted by class support, from the CSV
    # classify.py writes. Blank precision/recall mean the class never scored.
    nb = list(csv.DictReader(open(ROOT / "data" / "exports" / "nb_holdout.csv")))
    nb_n = sum(int(r["test_n"]) for r in nb) or 1
    wmean = lambda k: sum(float(r[k] or 0) * int(r["test_n"]) for r in nb) / nb_n
    per = {r["class"]: r for r in nb}
    methods = dict(con.execute("SELECT method, COUNT(*) FROM classification GROUP BY 1"))
    n_groups = q("SELECT COUNT(DISTINCT group_id) FROM syntactic_group")
    singletons = q("""SELECT COUNT(*) FROM
        (SELECT group_id FROM syntactic_group GROUP BY 1 HAVING COUNT(*)=1)""")
    # How few containment outcomes the long tail of one-off skeletons reduces to.
    singleton_verdicts = len({
        (s, matchertext.assess(s, sk)[1] or "outside")
        for s, sk in con.execute("""SELECT syntax_type, skeleton FROM syntactic_group
            WHERE group_id IN (SELECT group_id FROM syntactic_group
                               GROUP BY 1 HAVING COUNT(*)=1)""")})

    vals = [
        ("PublishedCVEs", num(published)),
        ("CVERecords", num(q("SELECT COUNT(*) FROM cve"))),
        ("InjectionCVEs", num(injection)),
        ("InjectionShare", pct(injection / published)),
        ("InjectionSharePrecise", pct(injection / published, 1)),
        ("InjectionCWEs", num(q("""SELECT COUNT(DISTINCT cwe_id) FROM cwe_assignment
                                   WHERE cve_id IN (SELECT cve_id FROM classification)"""))),
        ("InjectionKev", num(q("SELECT COUNT(*) FROM classification JOIN kev USING(cve_id)"))),
        # labeling layers
        ("MethodCwe", num(methods.get("cwe", 0))),
        ("MethodCweShare", pct(methods.get("cwe", 0) / injection)),
        ("MethodRule", num(methods.get("rule", 0))),
        ("MethodNb", num(methods.get("nb", 0))),
        ("MethodNbShare", pct(methods.get("nb", 0) / injection, 1)),
        ("MethodUnknown", num(methods.get("unknown", 0))),
        ("NbTestDocs", num(nb_n)),
        ("NbPrecision", f"{wmean('precision'):.3f}"),
        ("NbRecall", f"{wmean('recall'):.3f}"),
        ("NbCoverage", pct(float(nb[0]["coverage"]) if nb else 0)),
        ("NbPrecisionHtmlDom", f"{float(per['html_dom']['precision']):.2f}"),
        ("NbRecallHtmlDom", f"{float(per['html_dom']['recall']):.2f}"),
        ("NbPrecisionSql", f"{float(per['sql']['precision']):.2f}"),
        ("NbRecallSql", f"{float(per['sql']['recall']):.2f}"),
        ("NbPrecisionCodeEval", f"{float(per['code_eval']['precision']):.2f}"),
        ("NbRecallCodeEval", f"{float(per['code_eval']['recall']):.2f}"),
        ("MethodDeterministicShare",
         pct((methods.get("cwe", 0) + methods.get("rule", 0)) / injection, 1)),
        ("AuditPerMethod", num(export.AUDIT_PER_METHOD)),
        ("InjectionWithPoc", num(with_poc)),
        ("InjectionWithPocShare", pct(with_poc / injection)),
        ("PocRows", num(q("SELECT COUNT(*) FROM poc"))),
        # per-source PoC reach over the whole corpus, for \cref{sec:data}
        *[(f"Poc{''.join(c for c in s.title() if c.isalpha())}CVEs", num(n)) for s, n in con.execute(
            "SELECT source, COUNT(DISTINCT cve_id) FROM poc GROUP BY 1 ORDER BY 2 DESC")],
        ("KevRows", num(q("SELECT COUNT(*) FROM kev"))),
        ("VedasScored", num(q("""SELECT COUNT(*) FROM cve v JOIN exploit_score USING(cve_id)
                                 WHERE v.state='PUBLISHED'"""))),
        # payload-backed containment
        ("PayloadBackedCVEs", num(grouped)),
        ("DistinctSkeletons", num(q("SELECT COUNT(DISTINCT group_id) FROM syntactic_group"))),
        ("SingletonGroups", num(singletons)),
        ("SingletonGroupShare", pct(singletons / n_groups)),
        ("SingletonCVEShare", pct(singletons / grouped)),
        ("SingletonVerdicts", num(singleton_verdicts)),
        # The two dominant syntaxes, quoted in results.tex as a share.
        ("TopTwoShare", pct(q("""SELECT COUNT(*) FROM classification
                                 WHERE syntax_type IN ('html_dom','sql')""") / injection)),
        # Counts for the three largest groups the text names, looked up by their
        # exact skeleton so a changed skeleton shows up as 0 rather than silently
        # keeping a stale number.
        *[(f"Group{k}", num(skeleton_count(con, sk))) for k, sk in (
            ("AlertDocId", "< TAG > ALERT ( DOCUMENT . <id> ) </ TAG >"),
            ("AlertCookie", "< TAG > ALERT ( DOCUMENT . COOKIE ) </ TAG >"),
            ("Sleep", "SLEEP ( <n> )"))],
        # orthogonal subclass facets, keyed by (dimension, label)
        *[(f"Sub{d.title().replace('_', '')}{l.title().replace('_', '')}", num(n))
          for d, l, n in con.execute("""SELECT dimension, label, COUNT(*) FROM subclass
                                        WHERE dimension IN ('privilege','technique')
                                        GROUP BY 1,2""")],
        ("Contained", num(contained)),
        ("ContainedShare", pct(contained / grouped)),
        # The floor on the same denominator as the ceiling. ContainedShare is a
        # share of the payload-backed subset, so quoting it beside HostableShare
        # compares two different populations and makes the floor look larger than
        # the ceiling. This counts every CVE without a recoverable payload as
        # uncontained, which makes it a hard lower bound rather than an estimate.
        ("FloorShare", pct(contained / injection, 1)),
        ("InertCVEs", num(sum(inert.values()))),
        ("RejectedCVEs", num(sum(reject.values()))),
        ("OutsideCVEs", num(sum(outside.values()))),
        ("OutsideSemantic", num(semantic)),
        ("OutsideNonmatcher", num(nonmatcher)),
        ("SqlRejected", num(reject["sql"])),
        ("LdapInert", num(inert["ldap"])),
        ("LdapRejected", num(reject["ldap"])),
        # projection onto the full corpus
        ("HostableCVEs", num(hostable)),
        ("HostableShare", pct(hostable / injection)),
        ("HtmlDomCVEs", num(htmldom)),
        ("HtmlDomBacked", num(hd_backed)),
        ("HtmlDomJsSinks", num(outside["html_dom"])),
        ("JsSinkRate", pct(js_rate, 1)),
        ("JsSinkRemoved", num(removed)),
        ("CentralEstimate", num(central)),
        ("NaiveEstimate", num(round(naive))),
        ("NaiveShare", pct(naive / injection)),
        ("SkewCost", num(round(naive) - central)),
        ("CentralShare", pct(central / injection)),
        # payload corpora (fuzzdb / PayloadsAllTheThings / SecLists)
        ("CorpusPayloads", num(corpus_n)),
        ("CorpusHostable", num(corpus_hostable)),
        ("CorpusInert", num(corpus_inert)),
        ("CorpusRejected", num(corpus_reject)),
        ("CorpusInertShare", pct(corpus_inert / (corpus_inert + corpus_reject), 1)),
        ("CorpusRejectedShare", pct(corpus_reject / (corpus_inert + corpus_reject), 1)),
        # labeled ground truth
        ("GroundTruthCases", num(q("SELECT COUNT(*) FROM ground_truth"))),
        ("GroundTruthPairs", num(len(anchors))),
        ("GroundTruthResolved", num(len(resolved))),
    ]
    vals += sqli_macros(con)
    (OUT / "numbers.tex").write_text(
        HEADER + "".join(macro(k, v) for k, v in vals))
    (OUT / "tbl-mech.tex").write_text(HEADER + tbl_mech(inert, reject, outside))
    (OUT / "fig-tree.tex").write_text(HEADER + fig_tree(
        grouped, contained, sum(inert.values()), sum(reject.values()),
        sum(outside.values()), semantic, nonmatcher))
    (OUT / "tbl-syntax.tex").write_text(HEADER + tbl_syntax(con))
    (OUT / "tbl-strata.tex").write_text(HEADER + tbl_strata(strata))
    (OUT / "tbl-payload-corpus.tex").write_text(HEADER + tbl_payload_corpus(con))
    (OUT / "tbl-poc-sources.tex").write_text(HEADER + tbl_poc_sources(con))
    (OUT / "tbl-anchors.tex").write_text(HEADER + tbl_anchors(resolved))
    if con.execute("""SELECT COUNT(*) FROM sqlite_master
                      WHERE type='table' AND name='mt_sqli_combo'""").fetchone()[0]:
        (OUT / "tbl-sqli-arms.tex").write_text(HEADER + tbl_sqli_arms(con))
    print(f"wrote {len(vals)} macros and 6 tables to {OUT.relative_to(ROOT)}")
    con.close()


if __name__ == "__main__":
    run(argparse.ArgumentParser(description=__doc__).parse_args())
