//
// LanguageClassifier.hpp
// Author: Antoine Bastide
// Date: 24/03/2026
//

#ifndef LANGUAGE_CLASSIFIER_HPP
#define LANGUAGE_CLASSIFIER_HPP

#include <cstdint>
#include <string_view>

/// Detectable language categories for embedded string classification.
enum class Language : uint8_t {
  Unknown = 0,
  PlainText,
  // Structural patterns (Layer 1)
  URL,
  FilePath,
  FormatString,
  // Domain-specific languages
  SQL,
  HTML,
  XML,
  JSON,
  YAML,
  CSS,
  Regex,
  Shell,
  // Programming languages
  Python,
  JavaScript,
  TypeScript,
  Java,
  C,
  CPP,
  CSharp,
  Go,
  Rust,
  Ruby,
  PHP,
  Perl,
  Lua,
  Swift,
  Kotlin,
  R,
  Scala,
  Haskell,
  OCaml,
  Erlang,
  Elixir,
  Dart,
  Objective_C,
  GLSL,
  HLSL,
  // Auxiliary string buckets
  IdentifierLike,
  HexData,
  BinaryData,
  COUNT
};

/// Returns a human-readable name for the given language.
const char *LanguageName(Language lang);

/// Result of string fragment classification.
struct ClassificationResult {
  Language language;
  float confidence; // 0.0 to 1.0
};

/// Classify a string fragment into its most likely source language.
///
/// Uses a two-layer approach:
///   Layer 1: Deterministic structural detectors for high-precision patterns
///            (URLs, file paths, JSON, HTML, SQL, regex, etc.)
///   Layer 2: Naive Bayes trigram classifier for broad language coverage
///            (programming languages and domain-specific languages).
///
/// Layer 2 requires a trained model generated by train/generate_model.py.
/// Without a trained model, only Layer 1 structural detection is active.
///
/// @param body The extracted string content (without surrounding quotes).
/// @param minConfidence Minimum confidence threshold; returns Unknown below this.
/// @return The detected language and confidence score.
ClassificationResult ClassifyString(std::string_view body, float minConfidence = 0.5f);

#endif // LANGUAGE_CLASSIFIER_HPP
